title: Analytiq Hub
author:
  name: Andrei Radulescu-Banu
  email: "andrei@analytiqhub.com"
description: > # this means to ignore newlines until "show_excerpts:"
  Analytiq Hub provides custom AI solutions and expert guidance 
  for biotech and healthtech companies.

show_excerpts: false # set to true to show excerpts on the homepage
permalink: pretty
baseurl: ""


# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  #skin: classic
  skin: dark
  #skin: solarized-dark
  #skin: solarized

  # generate social links in footer
  social_links:
    twitter: bitdribble
    github:  andrei-radulescu-banu
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    linkedin: andrei-radulescu-banu
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - title: "Services"
    url: "/services"
  - title: "Resources"
    url: "#"
    children:
      - title: "Use Cases"
        url: "/use-cases"
      - title: "Technology"
        url: "/technology"
  - title: "Talks"
    url: "/talks"
  - title: "Blog"
    url: "/blog"
  - title: "About"
    url: "/about"
  - title: "Contact"
    url: "/contact"

# Footer sitemap - simplified navigation for footer display
site_map:
  - title: "Services"
    links:
      - title: "Services"
        url: "/services"
      - title: "Use Cases"
        url: "/use-cases"
      - title: "Technology"
        url: "/technology"
  - title: "Company"
    links:
      - title: "About"
        url: "/about"
      - title: "Team"
        url: "/team"
      - title: "Partners"
        url: "/partners"
  - title: "Resources"
    links:
      - title: "Blog"
        url: "/blog"
      - title: "Talks"
        url: "/talks"
      - title: "Open Source"
        url: "/open-source"

# Build settings
# theme: minima  # Removed - using Tailwind CSS instead

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-pdf-embed # Per example at https://github.com/MihajloNesic/minimal-mistakes-pdf-example/
 - jekyll-paginate-v2



future: true

# GitHub repository configuration
repository: bitdribble/bitdribble.github.io